### ISSUE TITLE
Chat Room GUI

### ISSUE THREAD

**Issue by adillon3** [SQL-Injectors-Saddleback/ChatClient#3]
As a client, I want to be able to send text messages, as well as picture messages to others in the chat room.

Acceptance Criteria
-Users will be able to compose and post text messages
-Users will be able to send pictures

**Comment by zerohezitation** [comment]
Sending messages works great, sending pictures works for the most part it still is not optimal to dynamically add pictures to the text area but is serialized and saved with the project and opened by the user
